networks:
  logsgo:
    name: logsgo

services:
  logsGo:
    image: saumyashah40/logsgo:dev
    container_name: logsgo
    networks:
      - logsgo
    ports:
      - "19091:19091"
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./store_config.yaml:/etc/logsgo/store_config.yaml
      - ./data:/data
    command:
      - --store-config-path=/etc/logsgo/store_config.yaml
      - --web-listen-addr=0.0.0.0:19091
      - --grpc-listen-addr=0.0.0.0:50051
      - --http-listen-addr=0.0.0.0:8080  # As this is a demo, we can do expose it to all interfaces :)

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - logsgo
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  example_app:
    image: saumyashah40/logsgo-example:latest
    container_name: example_app
    networks:
      - logsgo
    depends_on:
      - logsGo
      - minio
