// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: logs.proto

package logapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIngestor_UploadLog_FullMethodName  = "/logapi.LogIngestor/UploadLog"
	LogIngestor_UploadLogs_FullMethodName = "/logapi.LogIngestor/UploadLogs"
)

// LogIngestorClient is the client API for LogIngestor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogIngestorClient interface {
	UploadLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*UploadResponse, error)
	UploadLogs(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*UploadResponse, error)
}

type logIngestorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogIngestorClient(cc grpc.ClientConnInterface) LogIngestorClient {
	return &logIngestorClient{cc}
}

func (c *logIngestorClient) UploadLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, LogIngestor_UploadLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logIngestorClient) UploadLogs(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, LogIngestor_UploadLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogIngestorServer is the server API for LogIngestor service.
// All implementations must embed UnimplementedLogIngestorServer
// for forward compatibility.
type LogIngestorServer interface {
	UploadLog(context.Context, *LogEntry) (*UploadResponse, error)
	UploadLogs(context.Context, *LogBatch) (*UploadResponse, error)
	mustEmbedUnimplementedLogIngestorServer()
}

// UnimplementedLogIngestorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogIngestorServer struct{}

func (UnimplementedLogIngestorServer) UploadLog(context.Context, *LogEntry) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLog not implemented")
}
func (UnimplementedLogIngestorServer) UploadLogs(context.Context, *LogBatch) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLogs not implemented")
}
func (UnimplementedLogIngestorServer) mustEmbedUnimplementedLogIngestorServer() {}
func (UnimplementedLogIngestorServer) testEmbeddedByValue()                     {}

// UnsafeLogIngestorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogIngestorServer will
// result in compilation errors.
type UnsafeLogIngestorServer interface {
	mustEmbedUnimplementedLogIngestorServer()
}

func RegisterLogIngestorServer(s grpc.ServiceRegistrar, srv LogIngestorServer) {
	// If the following call pancis, it indicates UnimplementedLogIngestorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIngestor_ServiceDesc, srv)
}

func _LogIngestor_UploadLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogIngestorServer).UploadLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogIngestor_UploadLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogIngestorServer).UploadLog(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogIngestor_UploadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogIngestorServer).UploadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogIngestor_UploadLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogIngestorServer).UploadLogs(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// LogIngestor_ServiceDesc is the grpc.ServiceDesc for LogIngestor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIngestor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logapi.LogIngestor",
	HandlerType: (*LogIngestorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadLog",
			Handler:    _LogIngestor_UploadLog_Handler,
		},
		{
			MethodName: "UploadLogs",
			Handler:    _LogIngestor_UploadLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
